/**
 * @NApiVersion 2.1
 */

define(['../../../Helper/SuiteQL/suiteql', './timelineevent'],
    
    (suiteql, timelineevent) => {

        const createAtlTransactionTle = (options) => {

            // Reading the records generated by atlassianpullmr.js
            const objAtlTransaction = suiteql.execute({
                sqlfile: '../../NetSpot/sql/atlmarketplacetransaction.sql',
                custparam: {
                    paramid: options.id
                }
            });

            if (objAtlTransaction.status == 'SUCCESS') {
                
                if (objAtlTransaction.data.length > 0) {

                    const objData = objAtlTransaction.data[0];

                    if(objData.customerid != "" && objData.customerid != null){

                        const ntsptTle = timelineevent.create({
                            integration: 'atlmkplctransco',
                            data: objData
                        });

                        if (ntsptTle.status == 'FAILED'){

                            log.error({
                                title: 'SEND_ATL_TRANSACTION_CO_TLE',
                                details: ntsptTle.message
                            });
                        }
                    }

                    if(objData.technicalcontactid != "" && objData.technicalcontactid != null){

                        const ntsptTle = timelineevent.create({
                            integration: 'atlmkplctranstc',
                            data: objData
                        });

                        if (ntsptTle.status == 'FAILED'){
                            log.error({
                                title: 'SEND_ATL_TRANSACTION_TC_TLE',
                                details: ntsptTle.message
                            });
                        }

                    }

                    if(objData.billingcontactid != "" && objData.billingcontactid != null && objData.billingcontactid != objData.technicalcontactid){

                        const ntsptTle = timelineevent.create({
                            integration: 'atlmkplctransbc',
                            data: objData
                        });

                        if (ntsptTle.status == 'FAILED'){
                            
                            log.error({
                                title: 'SEND_ATL_TRANSACTION_BC_TLE',
                                details: ntsptTle.message
                            });
                        }
                    }

                } else {
                    return {
                        status: 'INFO',
                        message: "The query didn't find any records. Something could be wrong with the filters and joins in the `atlmarketplacetransaction.sql`."
                    }
                }
            } else {
                log.error({
                    title: 'SEND_ATL_TRANSACTION',
                    details: objAtlTransaction.message
                });
            }
        }

        const createAtlLicenseTle = (options) => {

            const objAtlLicense = suiteql.execute({
                sqlfile: '../../NetSpot/sql/atlmarketplacelicense.sql',
                custparam: {
                    paramid: options.id
                }
            });

            if (objAtlLicense.status == 'SUCCESS') {
                
                if (objAtlLicense.data.length > 0) {

                    const objData = objAtlLicense.data[0];

                    if(objData.customerid != "" && objData.customerid != null){

                        const ntsptTle = timelineevent.create({
                            integration: 'atlmkplclicenseco',
                            data: objData
                        });

                        if (ntsptTle.status == 'FAILED'){

                            log.error({
                                title: 'SEND_ATL_LICENSE_CO_TLE',
                                details: ntsptTle.message
                            });
                        }
                    }

                    if(objData.technicalcontactid != "" && objData.technicalcontactid != null){

                        const ntsptTle = timelineevent.create({
                            integration: 'atlmkplclicensetc',
                            data: objData
                        });

                        if (ntsptTle.status == 'FAILED'){
                            log.error({
                                title: 'SEND_ATL_LICENSE_TC_TLE',
                                details: ntsptTle.message
                            });
                        }

                    }

                    if(objData.billingcontactid != "" && objData.billingcontactid != null && objData.billingcontactid != objData.technicalcontactid){

                        const ntsptTle = timelineevent.create({
                            integration: 'atlmkplclicensebc',
                            data: objData
                        });

                        if (ntsptTle.status == 'FAILED'){
                            
                            log.error({
                                title: 'SEND_ATL_LICENSE_BC_TLE',
                                details: ntsptTle.message
                            });
                        }
                    }

                }
                else {
                    return {
                        status: 'INFO',
                        message: "The query didn't find any records. Something could be wrong with the filters and joins in the `atlmarketplacelicense.sql`."
                    }
                }
            }
            else{
                log.error({
                    title: 'SEND_ATL_TRANSACTION',
                    details: objAtlLicense.message
                });
            }
        }



        return {createAtlTransactionTle, createAtlLicenseTle}

    });
